project:
  type: website
  output-dir: ./docs

website:
  title: "Julien Vitay"
  navbar:
    background: black
    foreground: light
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: CV
      - research.qmd
      - publications.qmd
      - teaching.qmd
      - blog.qmd

  page-footer: 
    border: false
    center: "Julien Vitay" 

format:
  html:
    theme: [sandstone, assets/styles.scss]
    toc: true
    html-math-method: katex
    email-obfuscation: none

csl: assets/frontiers.csl
resources:
  - CNAME

