project:
  type: website
  output-dir: ../docs


csl: frontiers.csl

website:
  title: "Julien Vitay"
  navbar:
    background: dark
    foreground: light
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: CV
      - research.qmd
      - publications.qmd
      - teaching.qmd
      - blog.qmd
      - contact.qmd

  page-footer: 
    border: false
    center: "Julien Vitay - Chemnitz University of Technology" 

format:
  html:
    theme: [sandstone, styles.scss]
    toc: true
    html-math-method: katex
    email-obfuscation: none



