---
title: "Dr. habil. Julien Vitay"

toc: false
---

Researcher / lecturer at the Chemnitz University of Technology.


## Education

{{< fa solid graduation-cap size=lg >}} &nbsp; **Chemnitz University of Technology**  - Germany
<span style="float:right;">2017</span>

$\rightarrow$ Habilitation in Computer Science.


{{< fa solid graduation-cap size=lg >}} &nbsp; **Université Henri Poincaré Nancy-I** - France
<span style="float:right;">2006</span>

$\rightarrow$ PhD in Computer Science.



{{< fa solid graduation-cap size=lg >}} &nbsp; **École Supérieure d'Électricité (Supélec)**  - France
<span style="float:right;">2002</span>

$\rightarrow$ Engineering degree in Signal Processing and Microelectronics.



{{< fa solid graduation-cap size=lg >}} &nbsp; **Université Rennes-I** - France
<span style="float:right;">2002</span>

$\rightarrow$ Master of Science in Microelectronics.


## Experience


{{< fa solid person-chalkboard size=lg >}} &nbsp; **Chemnitz University of Technology** - Germany
<span style="float:right;">2011 - now</span>

$\rightarrow$ Researcher / lecturer in the faculty of Computer science.

* Research: 
    * Computational neuroscience: basal ganglia, dopamine, hippocampus.
    * Neuroinformatics: neurosimulator [ANNarchy](https://github.com/ANNarchy/ANNarchy)
    * Machine learning, reinforcement learning.
* Teaching: 
    * Neurocomputing / Machine Learning
    * Deep Reinforcement Learning
    * Computer Vision
    * Introduction to AI.
* Erasmus+ departmental coordinator.

---

{{< fa solid microscope size=lg >}} &nbsp; **WWU University of Münster**  - Germany
<span style="float:right;">2006 - 2011</span>

$\rightarrow$ Postdoc in the Institute of Psychology, lab of Markus [Lappe](https://www.uni-muenster.de/PsyIFP/AELappe), supervisor Fred Hamker.

* Research: 
    * Computational neuroscience: basal ganglia.

---

{{< fa solid school size=lg >}} &nbsp; **Inria Lorraine** - France
<span style="float:right;">2002 - 2006</span>

$\rightarrow$ PhD student in the Cortex team (LORIA Nancy), supervisors Frédéric Alexandre and Nicolas Rougier.

* Research: 
    * Computational neuroscience: basal ganglia, visual attention.
    * Robotics.
* Teaching (at the University of Nancy-I):
    * Computer architecture, Java, AI. 

