# Metadata
title: Deep Reinforcement Learning
author: Julien Vitay
email: julien.vitay@informatik.tu-chemnitz.de

# List of files to include
files:
    - 0-Introduction.md
    - 1.1-BasicRL.md
    - 1.2-DeepLearning.md
    - 2-Valuebased.md
    - 3.1-PolicyGradient.md
    - 3.2-ActorCritic.md
    - 3.3-ImportanceSampling.md
    - 3.4-DPG.md
    - 3.5-NaturalGradient.md
    - 3.6-OtherPolicyGradient.md
    - 4-RAM.md
    - 5-ModelBased.md
    - 6-Hierarchical.md
    - 7-Inverse.md
    - 8-Robotics.md
    - 9-Practice.md
    - 10-References.md

# Bibliography
bibliography:
    - /home/vitay/Biblio/bibtex/ReinforcementLearning.bib
    - /home/vitay/Biblio/bibtex/DeepLearning.bib
csl: assets/frontiers.csl


# CSS
css: assets/github.css
#mathjax: /usr/share/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML
mathjax: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML


# Latex
geometry: "margin=1in"
fontfamily: "times"
fontsize: "11pt"
header-includes:
    - \usepackage{setspace}
    - \onehalfspacing
    - \usepackage{titling}
    - \pretitle{\begin{center}\begin{bfseries}\begin{huge}}
    - \posttitle{\end{huge}\end{bfseries}\end{center}\vspace{2cm}}
